name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker image build -t mp4ansi:latest .

    - name: Prepare coverage
      run: |
        ID=$(docker create mp4ansi)
        docker cp $ID:/code/target/reports/mp4ansi_coverage.xml mp4ansi_coverage.xml
        sed -i -e 's,filename="mp4ansi/,filename="src/main/python/mp4ansi/,g' mp4ansi_coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: mp4ansi_coverage.xml
