name: build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    container: python:3.9-slim

    steps:
    - uses: actions/checkout@v2

    - name: Install pybuilder
      run: pip install pybuilder

    - name: Install dependencies
      run: pyb install_dependencies

    - name: Execute build
      run: pyb -X

    - name: Install Codecov requirements
      run: |
        apt-get update
        apt-get install -y bash curl
        sed -e 's,filename="mp4ansi/,filename="src/main/python/mp4ansi/,g' target/reports/mp4ansi_coverage.xml > coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml